################
### MONITORS ###
################

monitor = DP-2, 3440x1440@180.00Hz, 0x0, 1, bitdepth, 10
monitor = HDMI-A-2, preferred, 3440x0, 1, transform, 1


###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = dolphin
$menu = wofi


#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_MENU_PREFIX,arch- 

###################
### PERMISSIONS ###
###################

permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

################
### SOURCING ###
################

source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/look.conf
source = ~/.config/hypr/hyprland/input.conf
source = ~/.config/hypr/hyprland/windows-workspaces.conf
