exec-once = $terminal
exec-once = waybar & 
exec-once = swww-daemon &
exec-once = swaync &
exec-once = hypridle &
exec-once = flameshot &
exec-once = cupsd &
exec-once = sh ~/.scripts/run-wayvnc-main-monitor &
exec-once = wayvnc 0.0.0.0 -g --output=DP-2 &
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --watch cliphist store &
exec-once = /usr/lib/protonmail/bridge/bridge --grpc &
exec-once = hyprpm reload -n

exec = gsettings set org.gnome.desktop.interface gtk-theme "Adwita-dark" &
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" &
exec = kbuildsycoca6 &


